name: Generate JSON

on:
  schedule:
    - cron: '0 19 * * *'
  workflow_dispatch:

jobs:
  generate-j1:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Run Python Script
        run: |
          git config --global user.email "alaguku02@mail.com"
          git config --global user.name "Alagu Karuppiah"
          pip install -r requirements.txt
          python script.py
          git add NIFTY.json
          git commit -m "Update JSON file"
          git push
